### PR TITLE
removed dependency on GLEW

### PR DESCRIPTION
**Pull request by cxd4**

### CODE REVIEW

**Comment by LegendOfDragoon** [comment]
I had to remove https://github.com/cxd4/z64/blob/f290c4005c392ff62fbc3b040168811222b45467/src/rgl.cpp#L1371 in order to compile.

Edit: actually, after removing glew32.lib from the additional dependencies in linker input, it won't compile.

**Comment by cxd4** [comment]
> I had to remove

I'll take your word for it as I am not on Windows, which pushes link-time requirements earlier on.

> Edit: actually, after removing glew32.lib from the additional dependencies in linker input, it won't compile.

I'm guessing you mean, it won't "link".
Well then leave that in and don't remove it.

@purplemarshmallow can do the Windows side of things to remove the link-time dependency for Windows users, but for the time being, the dependency on GLEW (at least in the code) is removed here.

**Comment by LegendOfDragoon** [comment]
Part of the problem seems to be `#include "GL/glew.h"` in rgl.h. More work needs to be done after removing that though. For instance GLhandleARB is not defined.

**Comment by cxd4** [comment]
Hold off on merging this for a moment.  I never saw a second `#include "GL/glew.h"`.

**Comment by cxd4** [comment]
You had those errors because Windows only has core support for GL 1.1.

Other systems like Linux have at the very least core support for GL 1.4, so those errors applied not to me, but to Windows users.  Nevertheless based on deletion of the other include I finally had enough information to see what you meant.

Try now.

> For instance GLhandleARB is not defined.

It's not supposed to be.  Those are junk types imposed by Khronos; the issue is removing GLEW.

**Comment by LegendOfDragoon** [comment]
ok.

I get a few errors.

```
1>rgl.cpp(823): error C3861: 'glActiveTextureARB': identifier not found
1>rgl.cpp(832): error C3861: 'glMultiTexCoord2fARB': identifier not found
```

**Comment by cxd4** [comment]
Where though.

**Comment by cxd4** [comment]
How about now?

**Comment by LegendOfDragoon** [comment]
https://github.com/cxd4/z64/blob/no-more-GLEW/src/rgl_rendermode.cpp#L248 and L270 need to be changed. After fixing that, it seems to work.

**Comment by cxd4** [comment]
One more commit to print functions that failed to load, in case somebody's video driver/implementation actually cannot access those extensions and features and be able to use the plugin anyway.  This way, the user can see why.  (Except `printf()` won't really show anything if you're on Windows unless you launched the emulator from a command prompt...if anyone knows of some central function this plugin uses for OS-specific message tidiness I can adjust that.)

**Pull request merged**
